### PR TITLE
Improve chinese translation

### PR DESCRIPTION
**Pull request by Eustiya**
this version is Azakoyin translated on the basis of my translation.he doesn't know how to use github, so let me launch pull request.The version corrects almost all previous problems,Azakoyin actually played the mod once and finally translated it.So the quality is very high.Since then, the translated entry may not need to be corrected.

I found the entry 'wiki.ic2.translated' should be write it like this 'ic2.wiki.translated' to display content

### CODE REVIEW

**Comment by Speiger** [comment]
Thank you so much to the both of you!
I will integrate that in the next few days.
Though the next patch is a bit further away.

**Comment by Speiger** [comment]
@Eustiya i am truly sorry i think syncing to latest translations made the merging kinda impossible.
Could you update it so it can be merged without issues?
I am worried if i pick the translation i am picking the wrong one ^^"

**Comment by Speiger** [comment]
(Also I added a few new translations in the stats section)

**Comment by Eustiya** [comment]
Sure,this new one.Is there anything else I can do for you？

**Comment by Speiger** [comment]
@Eustiya well i added new entries in the "stats.en_us" if you want to.
I am still testing the version before release so i ensure the nastier bugs were fixed.

**Comment by Eustiya** [comment]
@Speiger yes, of course

**Comment by Q-zed-D** [comment]
It looks like they're translated by translator apps. Sometimes I CANNOT read in Chinese but CAN read in English.

**Comment by Eustiya** [comment]
> It looks like they're translated by translator apps. Sometimes I CANNOT read in Chinese but CAN read in English.

I DO NOT think this translation will be perfect. What do you think is wrong? Please point it out one-on-one

**Comment by Eustiya** [comment]
> It looks like they're translated by translator apps. Sometimes I CANNOT read in Chinese but CAN read in English.

You can also try to use translator apps to see how the effect will be

**Comment by Q-zed-D** [comment]
> > It looks like they're translated by translator apps. Sometimes I CANNOT read in Chinese but CAN read in English.
> 
> You can also try to use translator apps to see how the effect will be

确实不全是机翻的，但机翻味还是太重了，如果可以的话，我自己重新翻译了很多，还参考了一些老版本的翻译以保证原汁原味，不知可否采纳？

**Comment by Eustiya** [comment]
> 

非WIKI部分已经没有机翻部分了，全是肉眼看过去一个一个词翻译的，机翻内容只是作为以前的参考，新的翻译都是对着英文一个一个翻的，机翻味太重了，你不能光说不举证吧。这里Azakoyin哥们贡献了很多，WIKI部分后面确实是有点摆烂了，可能是有极少部分遗漏了。许多内容都是经过斟酌查阅了相关内容才翻的。你要是能拿出更好的我也不阻拦你，但是说这个文本是机翻的实在太令人难过了

**Comment by Eustiya** [comment]
@Q-zed-D 你可以直接拉取请求的，这个我无所谓

**Pull request merged**
