### PR TITLE
Add Korean translation

### PR DESCRIPTION
**Pull request by kwonms871**
Hello, I'm a Korean player. When I saw this mod posted on 1.19 last year, I checked and found that there was no Korean language and made a translation file. However, the translation can be very strange because it was made using a translator.

### CODE REVIEW

**Comment by Speiger** [comment]
@kwonms871 thank you.
Please note that yesterday there was a patch made with a few new additions.
it is only a tiny patch.
https://github.com/TinyModularThings/IC2Classic/commit/468fc7d6e01f9dc775fbf033cbb8d6c65c88d531

In the wiki section there is "Translated" where you can insert your name if you want to.
And "translatedBy" is just the header name that should be just translade.

I will import it when the next patch is being made.
Which should be in a few days.

**Comment by kwonms871** [comment]
Modified to fit 468fc7d.

**Comment by Speiger** [comment]
Thank you. I will in a couple hours finish the patch :3

**Comment by Speiger** [comment]
Merging

**Pull request merged**
