### PR TITLE
PlasmafierGui and MassFabricatorGui

### PR DESCRIPTION
**Pull request by Christofmeg**
[IC2C-UU-Matter/tree/1.12.2](https://github.com/Christofmeg/IC2C-UU-Matter/tree/1.12.2) need these two guis in order to add recipeClickAreas to Mass Fabricator and Plasmafier.

image
image

Thank you :)

### CODE REVIEW

**Comment by Speiger** [comment]
@Christofmeg I can't accept this code due to it causing ic2 to be open sourced.
I am already aware of your addon.
And think about importing it at some point (with your permission). 

But it isn't a goal at the moment, also addons should allow to exist and not be instantly imported either.

That being said: I would highly suggest you don't open source IC2 Source code because that is being at risk of being taken down.
Now if you need to do patch functions you write the patches and only take the "required code" to make it work but not everything.

**Comment by Christofmeg** [comment]
@Speiger It would be cool to merge my mod into the main mod at some point. I do agree that 
> addons should allow to exist and not be instantly imported

While that is not a goal, you could add these files:

#### MassFabricatorGui.java
```
package ic2.core.inventory.gui.custom;

import ic2.core.inventory.container.ContainerComponent;
import ic2.core.inventory.gui.GuiComponentContainer;
import net.minecraftforge.fml.relauncher.Side;
import net.minecraftforge.fml.relauncher.SideOnly;

@SideOnly(Side.CLIENT)
public class MassFabricatorGui extends GuiComponentContainer {

    @SuppressWarnings("rawtypes")
    public MassFabricatorGui(ContainerComponent inventorySlotsIn) {
        super(inventorySlotsIn);
    }
}
```


#### PlasmafierGui .java
```
package ic2.core.inventory.gui.custom;

import ic2.core.inventory.container.ContainerComponent;
import ic2.core.inventory.gui.GuiComponentContainer;
import net.minecraftforge.fml.relauncher.Side;
import net.minecraftforge.fml.relauncher.SideOnly;

@SideOnly(Side.CLIENT)
public class PlasmafierGui extends GuiComponentContainer {

    @SuppressWarnings("rawtypes")
    public PlasmafierGui(ContainerComponent inventorySlotsIn) {
        super(inventorySlotsIn);
    }
}
```


#### TileEntityMassFabricator.java
`import ic2.core.inventory.gui.custom.MassFabricatorGui;`

Change return value in:
```
   public Class<? extends GuiScreen> getGuiClass(EntityPlayer player) {
      return GuiComponentContainer.class;
   }
```
to the following:
```
    @Override
    public Class<? extends GuiScreen> getGuiClass(EntityPlayer player) {
        return MassFabricatorGui.class;
    }
```


#### TileEntityPlasmafier.java
`import ic2.core.inventory.gui.custom.PlasmafierGui;`

Change return value in:
```
   public Class<? extends GuiScreen> getGuiClass(EntityPlayer player) {
      return GuiComponentContainer.class;
   }
```
to the following:
```
    @Override
    public Class<? extends GuiScreen> getGuiClass(EntityPlayer player) {
        return PlasmafierGui.class;
    }
```

Or do you want them uploaded elsewhere?

**Comment by Speiger** [comment]
@Christofmeg nah this is fine.
I already checked out your code space :)
So i know how to integrate it.

> While that is not a goal, you could add these files:

I Phrased that horribly. But what i meant to say is:
Just because you make an addon doesn't mean i should automatically import it.
That addon is your work, so you should get at least something back/credits for your work.
And that usually gets lost during addon importing.

Though ill keep in mind that i have your permission to include it :)
And i might do it at some point.
Until then thanks :)

**Comment by Christofmeg** [comment]
@Speiger If you import the addon it would be nice to get contributor/member role on Curseforge (and Modrinth if you ever decide to upload there). 

I created this pull request because [IC2C-UU-Matter](https://github.com/Christofmeg/IC2C-UU-Matter/blob/1.12.2/src/main/java/com/christofmeg/ic2cuumatter/integration/jei/ModJEIPlugin.java#L54&L56) needs TileEntityPlasmafier and TileEntityMassFabricator to return their own seperate gui class: `PlasmafierGui.class`/`MassFabricatorGui.class` in order to make addRecipeClickArea (the **`Show Recipe`** recipe feature) work.

**Pull request closed without merging**
