### PR TITLE
Updated version in gradle, for new api build

### PR DESCRIPTION
**Pull request by modmuss50**
After this has been merged build on jenkins.

### CODE REVIEW

**Comment by Speiger** [comment]
thanks forgot that^^

**Comment by Speiger** [comment]
By the way @modmuss50 jenkins do not allow me to update the api. (the run compile or whatstocallit is not there)

**Comment by modmuss50** [comment]
are you logged in?

**Comment by Speiger** [comment]
Yeah

**Comment by Speiger** [comment]
@modmuss50

**Comment by modmuss50** [comment]
I will have a look

**Comment by Speiger** [comment]
kk

**Comment by modmuss50** [comment]
It should allow you to...

**Comment by modmuss50** [comment]
http://modmuss50.me:8080/job/IC2Classic/ that page should have a build now button

**Comment by Speiger** [comment]
well the update build/rebuild button is missing (and i saw it)
And nope i have that link already open

**Comment by modmuss50** [comment]
try once more, If not I will build it now and fix it for later

**Comment by Speiger** [comment]
did not work.

**Pull request merged**
