### PR TITLE
Chinese translation fix

### PR DESCRIPTION
**Pull request by Q-zed-D**
Fix a lot chinese text, making it easier to understand

### CODE REVIEW

**Comment by Speiger** [comment]
@Q-zed-D thank you for the submission :)
@Eustiya since you did the original translation. I would like a review from you, since i can't really review it myself.
Please be reasonable :)

**Comment by Eustiya** [comment]
> @Q-zed-D thank you for the submission :) @Eustiya since you did the original translation. I would like a review from you, since i can't really review it myself. If that is possible. Please be reasonable :)

This translation is indeed better, merge it, but I don't quite agree with some translations.
比如导线翻译成电缆更好，传输的不是什么低压电

**Comment by Speiger** [comment]
> This translation is indeed better, merge it, but I don't quite agree with some translations.
> 比如导线翻译成电缆更好，传输的不是什么低压电

Huh, well i planned if you give your green light to merge it tomorrow.

**Comment by Eustiya** [comment]
> > This translation is indeed better, merge it, but I don't quite agree with some translations.
> > 比如导线翻译成电缆更好，传输的不是什么低压电
> 
> Huh, well i planned if you give your green light to merge it tomorrow.

Thank you for your trust, but I am busy now, so just merge.I took a look at what he submitted, and translation is really better in many places.

**Comment by Q-zed-D** [comment]
> 

Thanks for your advice. I considered "cable" and I think “导线” is a bit less accurate then “电缆” but it's used in IC2exp and IC2C old versions. There's no need to correct it because most players approve it then it's correct.

**Comment by Eustiya** [comment]
> > 
> 
> Thanks for your advice. I considered "cable" and I think “导线” is a bit less accurate then “电缆” but it's used in IC2exp and IC2C old versions. There's no need to correct it because most players approve it then it's correct.

But there's nothing wrong with correcting your mistakes. Just merge it. I am too busy to care about this.I hope you can also translate the wiki part.

**Comment by Q-zed-D** [comment]
> > > 
> > 
> > 
> > Thanks for your advice. I considered "cable" and I think “导线” is a bit less accurate then “电缆” but it's used in IC2exp and IC2C old versions. There's no need to correct it because most players approve it then it's correct.
> 
> But there's nothing wrong with correcting your mistakes. Just merge it. I am too busy to care about this.I hope you can also translate the wiki part.

以防你看不懂我用中文再说一遍吧。固然“电缆”比“导线”更准确更符合"cable"的游戏表现和实际意思，但用“导线”的翻译是因为实验版和以往的经典版一直都是用的这个翻译，大家都习惯并认可了那这就是对的，没有必要再更正了，不然我还是认同你说的“电缆”的翻译的。所以我站“导线”。

**Comment by Speiger** [comment]
@Q-zed-D From my rough google translation your argument partly was:
"I did it that way because it had been always that way".
While I sometimes agree with that I also see it, after being proven multiple times, as a really weak Argument. 
There should be also different reasons why things should stay the way they were.

I know that i know very little about Chinese, but i am still the person you have to convince to take the changes in.

This is nothing against you, it is just to point out that reasons like "It has been always that way" are not always a valid reasons.

**Comment by Eustiya** [comment]
> > > > 
> > > 
> > > 
> > > Thanks for your advice. I considered "cable" and I think “导线” is a bit less accurate then “电缆” but it's used in IC2exp and IC2C old versions. There's no need to correct it because most players approve it then it's correct.
> > 
> > 
> > But there's nothing wrong with correcting your mistakes. Just merge it. I am too busy to care about this.I hope you can also translate the wiki part.
> 
> 以防你看不懂我用中文再说一遍吧。固然“电缆”比“导线”更准确更符合"cable"的游戏表现和实际意思，但用“导线”的翻译是因为实验版和以往的经典版一直都是用的这个翻译，大家都习惯并认可了那这就是对的，没有必要再更正了，不然我还是认同你说的“电缆”的翻译的。所以我站“导线”。
你这态度也忒差了一点，这个英文我会看不懂吗，我的意思以前那是不对的，而且电缆并不是没有在以前版本翻译中有使用过，现在这个ic2中使用这个翻译有什么问题呢？

**Comment by Eustiya** [comment]
> @Q-zed-D From my rough google translation your argument partly was: "I did it that way because it had been always that way". While I sometimes agree with that I also see it, after being proven multiple times, as a really weak Argument. There should be also different reasons why things should stay the way they were.
> 
> I know that i know very little about Chinese, but i am still the person you have to convince to take the changes in.
> 
> This is nothing against you, it is just to point out that reasons like "It has been always that way" are not always a valid reasons.


I am glad someone can take over this job and continue to maintain this translated text, but I don't want to spend too much time on these debates, so just merge it directly

**Comment by Q-zed-D** [comment]
> @Q-zed-D From my rough google translation your argument partly was: "I did it that way because it had been always that way". While I sometimes agree with that I also see it, after being proven multiple times, as a really weak Argument. There should be also different reasons why things should stay the way they were.
> 
> I know that i know very little about Chinese, but i am still the person you have to convince to take the changes in.
> 
> This is nothing against you, it is just to point out that reasons like "It has been always that way" are not always a valid reasons.

After communicating with some translators, we found that “导线” usually stands for "wires" and “电缆” usually stands for "cables". They should be different while cables are insulated and wires are not. But they're called the same "cable" in IC2. We resulted in "绝缘导线"(insulated wire) for insulated cables and “导线”(wire) for cables without inslation.

**Comment by Q-zed-D** [comment]
For example, "copper cable" is a bunch of copper wires but not copper cable. In China, ”导线“ is similar to ”电缆“ and people don't tell them apart in daily life unless you must tell the difference.

**Comment by Eustiya** [comment]
> 

导线与电缆区别就跟英语中tube和pipe一样。我认为后者会是更好的翻译。The difference between “导线” and “电缆” is just like the difference between tube and pipe in English. I think it will be better to translate it into the latter, that's all.

**Pull request merged**
