### PR TITLE
Adding the Ukrainian language

### PR DESCRIPTION
**Pull request by pgmtags**

### CODE REVIEW

**Comment by Speiger** [comment]
@pgmtags since this pull request has been stale for 3 weeks, i am giving a weeks notice.
You have till the end of next week to finish your translations otherwise i am closing this pull request.

**Comment by pgmtags** [comment]
> @pgmtags since this pull request has been stale for 3 weeks, i am giving a weeks notice. You have till the end of next week to finish your translations otherwise i am closing this pull request.

That's why I labeled it as a draft to show that the work is ongoing, not as a final request to the pool.

**Comment by pgmtags** [comment]
@Speiger There are problems with the display of text in the Wiki, namely (ш, щ & ф). 
I don't know how this can be fixed, if at all, but it's a bit of a nuisance. In the russian translation, it is similar.

image

**Comment by Speiger** [comment]
@pgmtags I am using minecrafts font.
This might be a minecraft bug then not an ic2c one.

**Comment by pgmtags** [comment]
> @pgmtags I am using minecrafts font. This might be a minecraft bug then not an ic2c one.

Oh, then okay

**Comment by Speiger** [comment]
note wiki isn't required to be translated.
That should be a last priority.

**Comment by Speiger** [comment]
@pgmtags as long as you keep a decent progress up and be ready by mid/end of next week I don't mind giving you a bit of extra time.
The point was giving you a reason to finish it, because the next update will be at least 4-6 ish months from now because IRL stuff is coming up.

**Comment by pgmtags** [comment]
> @pgmtags as long as you keep a decent progress up and be ready by mid/end of next week I don't mind giving you a bit of extra time. The point was giving you a reason to finish it, because the next update will be at least 4-6 ish months from now because IRL stuff is coming up.

My friend and I plan to finish the wiki translation with corrections in about a week. 
Almost 200 thousand characters, of which approximately 64k were translated

**Comment by pgmtags** [comment]
@Speiger I believe the translation is already quite good. There are a couple of things I'd like to correct, such as long titles that may exceed the boundaries, but overall, the translation is ready.

**Comment by pgmtags** [comment]
@Speiger 
image
I've never heard of it, and I haven't found any mention of it in the mod
Is this an upcoming update?

**Comment by Speiger** [comment]
@pgmtags i updated the translations to include next patches content too.
Monday is the planned release date that should be 48-60 hours. Which should be plenty to get the rest of the changes in.

**Comment by pgmtags** [comment]
@Speiger, we're finished

**Comment by Speiger** [comment]
@pgmtags thank you for completing it.
Also sorry for putting such a hard deadline on it ^^"
I just wanted to ensure that it actually gets in.

**Comment by pgmtags** [comment]
@Speiger, will there be further updates after 2.0.1.9 in the near future?

**Comment by Speiger** [comment]
@pgmtags If there is a bug report that is critical enough yes.
Otherwise I will wait a couple months till doing the next patch.
If you want to do another translation patch you can start it and once it is ready I will evaluate if i have time to make an update.

**Comment by pgmtags** [comment]
I understand, I've accumulated a few translation corrections now

I also want to ask about liquids: _honey_, _chocolate_, which ic2 adds, 
I would like to translate them, but the logical option of inserting `"fluid.ic2.chocolate/honey"` did not work

**Comment by CrossVas** [comment]
> I understand, I've accumulated a few translation corrections now
> 
> I also want to ask about liquids: _honey_, _chocolate_, which ic2 adds, 
> I would like to translate them, but the logical option of inserting `"fluid.ic2.chocolate/honey"` did not work
> 
> imageimage
> 
> 

fluid_display is basically an instance of ItemStack that use fluids icon for display.
IC2Classic does not add these fluids, it iterates through every fluid available in the game and make it's own fluid_display.
So these are fluids from another mod, even if it has ic2 in its name.

**Comment by pgmtags** [comment]
Understood, thanks for the explanation 🫡

**Pull request merged**
